### ISSUE TITLE
summer review checklist - draft 

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/website#738]
# DRAFT: Summer building block updating sprint

Background: Our content (e.g., building blocks and tutorials) has been developed over a three-year period, with various RAs and faculty, at various training levels. Also, our platform has been technically developing throughout this time. As a result, the quality of our content varies: some have never been revised!

Purpose: The purpose of this summer sprint is to __test__, and __update__ existing content, with the overall goal to improve the quality of our content (e.g., by enhancing user experience, reflecting the latest tools or versions, improving clarity and accuracy, etc.).

Before starting, read our [contribution/style guide](https://tilburgsciencehub.com/tutorials/more-tutorials/contribute-to-tilburg-science-hub/style-guide/).

Please then follow this checklist when updating our content:

1. "Do" the content
A first reality check can be conducted by actually WORKING with our content. Just read the building block or tutorial from the perspective of a new user.

Ask yourself the following questions:
- [ ] a. Is it clear what you will learn after reading the building block?
- [ ] b. Is the language professional and clear, or does the content come across as amateurish?
- [ ] c. Do you run into any issues when working on this building block? Are the visuals clear? 

Write down any weird things that you would like to fix and keep these notes.

2. Consider the checklist below and complement your initial check with these (more formal) dimensions

- [ ] **Keywords and Metadata:**
   - Ensure we have complete metadata in our `.md` files - sometimes, keywords were only loosely entered. Can you expand them? Also, use ChatGPT or similar AI tools to generate relevant other keywords.
- [ ] **Section structure and learning goals:**
   - Identify a few (say, 1-3) learning goals/objectives of the building block or tutorial, and highlight them at the start.
- [ ] **Title and Headings within the Content:**
   - Update titles and headings to create a clear and descriptive language that accurately reflects the content's focus.
- [ ] **Grammar and Style:**
   - Use Grammarly or other language tools to review and correct any grammatical errors or writing inconsistencies in the content.
- [ ] **Use of Code Tabs:**
   - Check that code that is most optimally presented in a code box is actually included in the code box.
   - If software packages are missing from the code tab (e.g., Stata, R, Python) and you have the expertise, then please add the implementation for the other software packages.
- [ ] **Use of Explanation Boxes:**
   - Ensure that explanation boxes are used effectively where necessary (e.g., info, warning), providing additional context, tips, or warnings to the users.
- [ ] **Media and Visuals:**
   - Review and update images or screenshots to enhance the understanding of the content.
   - Add new visuals where this is needed.
   - Add proper image descriptions for accessibility. 
- [ ] **Links and References:**
   - Verify that all links and references are still valid and point to the correct resources. Use persistent links where possible.
- [ ] **Version Compatibility:**
   - Ensure that the content is compatible with the latest versions of relevant software packages and tools.

3. Work on your changes and commit/do a PR (for testing and reviewing)

- Now you have a good idea of what you need to fix. Create a separate branch for your update, and commit frequently while doing your changes.
- Ask another RA to check your update and point out any other inconsistencies/problems.
- Make a pull request once the content is ready for review.

Remember to create separate branches for each update, and submit pull requests once the content is ready for review. Let's collaborate and make sure Tilburg Science Hub is even more valuable for our community.

**Comment by lachlandeer** [comment]
Closing since we completed a round on this last summer. We can revist this summer if needed
